### ISSUE TITLE
Layout - Component's attached hook not being called

### ISSUE THREAD

**Issue by alvarezmario** [aurelia/templating-router#37] opened 2016-08-20 03:59 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
LinuxMint

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.42

* **Browser:**
Chrome 52

* **Language:**
ESNext

**Current behavior:**
When using layouts, components attached hook is not being called

**Expected/desired behavior:**

* **What is the expected behavior?**
 Attached method should be called

* **What is the motivation / use case for changing the behavior?**

**Comment by Alexander-Taran** [comment] 2016-09-14 05:52
duplicate of #34

**Comment by EisenbergEffect** [comment] 2016-09-28 15:14
Closing as duplicate.

**Closed by EisenbergEffect** 2016-09-28 15:14 UTC
Labels: bug
