### ISSUE TITLE
Unhandled errors in route view models are not logged

### ISSUE THREAD

**Issue by antonmos** [aurelia/templating-router#44] opened 2016-11-05 15:41 UTC
**I'm submitting a bug report**

* **Library Version:**
aurelia-templating@1.1.2",
:aurelia-templating-binding@1.0.0",
aurelia-templating-resources@1.1.1",
aurelia-templating-router@1.0.0",

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.3.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all 
* **Language:**
all 

**Current behavior:**
 Errors thrown from route view (e.g. invalid expression in a binding `value.bind="${foo}"`) or an error throw from a view model are not logged in the console and the route view fails to render

Note that the same types of errors thrown in the main view/view model (app.html/app.js), DO get correctly logged.

This makes debugging very difficult: to find an error introduced during refactoring that touched multiple files, i have to binary search the change set by commenting out sections of the app.

I reproduced this in https://gist.run/?id=e0495dba6f0db86a91b64af9c0199345

Thanks!

**Comment by swalters** [comment] 2016-11-05 18:29
I've been seeing this in my application as well.  I recently moved from webpack to cli and thought that must be the reason.  Maybe this was broken in a recent release.

**Comment by EisenbergEffect** [comment] 2016-11-05 18:44
Closing this as a duplicate. It is a regression in the logging system. Fix is going out this week.

**Comment by EisenbergEffect** [comment] 2016-11-05 18:44
Apologies for that!

**Closed by EisenbergEffect** 2016-11-05 18:44 UTC

**Comment by antonmos** [comment] 2016-11-05 18:46
Thanks! where is the fix being tracked?

**Comment by EisenbergEffect** [comment] 2016-11-05 18:47
It's already merged into the logging repo. We just need to do a release. That should go out early this week.
