### ISSUE TITLE
Seems like I cant use bindings to use layoutViewModels properties in layoutView.

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/templating-router#34] opened 2016-07-28 10:04 UTC
**I'm submitting a bug report**
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.2.0
  
  
- **NPM Version:**
  3.8.9
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.32
  
  
- **Browser:**
  all
- **Language:**
  TypeScript X.X 

**Current behavior:**
Properties declared in layoutViewModel are not getting rendered in layoutView

**Expected/desired behavior:**
Having defined a module and a view for a layoutViewModel on a route.
I was expecting to be able to bind to layoutViewModels properties on layoutView

- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
  I am creating a nav/details layout with a collapsible side-bar which i would like to reuse.
  Layout was supposed to abstract the collapsing behavior away.

**Comment by chapma26** [comment] 2016-08-30 23:48
I can confirm the same issue. It seems the view model's constructor and attached functions are being called but no binding occurs.

**Comment by alpox** [comment] 2016-08-31 19:22
I can confirm this too. No bindings are possible in the layout views.

**Comment by d13** [comment] 2016-09-01 21:13
This sounds similar to an issue I'm getting as well. You can see it happening here: https://gist.run/?id=946bc745d16ee7888e7bd069aed344e0

**Comment by larsfjerm** [comment] 2016-09-13 14:52
+1

**Comment by Meyce** [comment] 2016-09-21 18:37
Any update on this?

**Comment by Alexander-Taran** [comment] 2016-09-21 20:58
The workaround would be to use another component with slots instead of layout.

**Comment by Creadigme** [comment] 2016-10-25 08:00
@Alexander-Taran @EisenbergEffect  Have you tried or find a working workaround for this issue ? LayoutView is a great feature but unusable in large project without support of components.

**Comment by Alexander-Taran** [comment] 2016-10-29 14:46
@Creadigme, no since we have a page or two for now which could benefit from this, we just copy pasted the functionality and are using the child router for details view. Which is not optimal, but we can live with it for now.

**Comment by Creadigme** [comment] 2016-10-29 15:45
@Alexander-Taran 

@joelcoxokc's pull request (https://github.com/aurelia/templating-router/pull/41) fixed the custom element "attached" issue (if we specify a layoutViewModel), thus it is already a step for our project.

But a big issue appear (for our need) : Layout is regenerated when you navigate to another page (even if it's the same layout). Therefore all custom elements in the layout are also recreated.

I work on a fix for this issue.

**Comment by aegenet** [comment] 2016-11-01 19:49
Custom elements support and layout not regenerated at each navigation (wip) : 
https://gist.run/embed.html?id=58858f211ec830d78fdd4f830115ec81

layout-router.view.js is based from the @joelcoxokc pull request.

The idea is here and it seem work, but as I don't know much more about aurelia templating, my "_clearSlot" function is a bit ugly. I can't find good way to clear slots.

For now, fallback slot don't work in the layout (linked to my _clearSlot).

**Comment by joelcoxokc** [comment] 2016-11-04 12:58
@egenet. Use viewSlot.removeAll()

However if there were animations, it will return a promise. So do. 

`Promise.resolve( viewSlot.removeAll() ).then(`

**Comment by aegenet** [comment] 2016-11-04 13:17
@joelcoxokc Can you fork my gist and provide a sample if you have few minutes ? Because I have already tried (bad way maybe). Thank you.

**Comment by jdemeuse1204** [comment] 2016-11-05 19:27
+1

**Comment by EisenbergEffect** [comment] 2016-11-13 06:58
@charlespockert Would you be able to take a look at this? Since you did the original layout implementation, I figure you would be the best person to correct this bug. Thanks!

**Comment by EisenbergEffect** [comment] 2016-11-28 05:37
Fixed in 7de185425397434122c5008bbbb46122500e16f4
If you have additional fixes, feel free to create a new PR from this latest version.

**Closed by EisenbergEffect** 2016-11-28 05:37 UTC
Labels: bug
