### ISSUE TITLE
route-href should be more tolerant to undefined params

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/templating-router#21] opened 2015-12-23 17:40 UTC
Given a view with this:

```
  <a route-href="route: myroute; params.bind: { id: data.id }">
    ${data.name}
  </a>
```

if `data` comes in late (async call) the `route-href` (`RouteRecognizer` in fact) throws this error as soon as the view loads:

```
ERROR [route-href] Error: A value is required for route parameter 'id' in route 'myroute'.
```

And then, when the `data` arrives the `href` is updated and everything is fine. The only way to avoid the error is to use `if.bind="data"` on the `<a>` element.

I feel like `route-href` should simply not set the `href` attribute on the `<a>` element until the `params` are available, the same way most binding tolerate the source to be undefined (`<div>${{this.might.not.be.defined.until.later}}</div>`).

**Comment by stalniy** [comment] 2016-03-25 07:27
Agree on this

**Comment by Gheoan** [comment] 2016-03-25 10:17
If you use the router you can return a `Promise` from the `activate` method on the view-model and Aurelia will not bind the view until after the `Promise` is fulfilled.

**Comment by DevNebulae** [comment] 2016-03-30 11:06
I also want to add to this that this also occurs when you want to have a dynamic route on an `href`.

```
<a route-href="route: ${var}"></a>
<a route-href="route: ${routeFunction()}></a>
```

**Comment by bryanrsmith** [comment] 2016-03-31 04:03
> I feel like route-href should simply not set the href attribute on the <a> element until the params are available

I disagree for two reasons:

1. There is no way to tell the difference between data that hasn't loaded yet and a mistyped binding or other mistake that will cause the binding to never succeed. I think it's important to provide an error message for a broken binding.
2. Showing the user a link that won't work is confusing UI, and I don't think it's something most people would want.

What do you think, @EisenbergEffect ?

**Comment by EisenbergEffect** [comment] 2016-03-31 05:59
@bryanrsmith I agree. However, I can understand the use case provided by @DevNebulae What if we provided another property on the `route-href` that let you opt into the behavior he's asking for?

**Comment by EisenbergEffect** [comment] 2016-03-31 06:02
Though I'm not sure about the specific example given...I think in that case I would be likely to just bind the straight `href`. @DevNebulae Can you provide some more explanation for your examples?

**Comment by DevNebulae** [comment] 2016-03-31 06:41
@EisenbergEffect What I am trying to do is create an icon in a toolbar to route to different modules within my Aurelia application. My idea was to do this:

**Javascript (simplified)**

```
export class Toolbar {
    //Binding to a variable
    @bindable route;

    //Binding to a getter
    get routeFunction() {
        return this.route; //Or a route from a model
    }
}
```

**HTML**

```
<template>
    <a route-href="route: ${route};">
        <!--Clickable visuals-->
    </a>
</template>
```

```
<template>
    <a route-href="route: ${routeFunction};">
        <!--Clickable visuals-->
    </a>
</template>
```

I also foresee a problem when you have a dynamic menu. Meaning the options in a menu can change upon data in a database. I would like the `route-href` still to check whether or not the route is there, but maybe upon activation (read: click event).

**Comment by jon123** [comment] 2016-04-16 18:41
Just ran into this case myself.  To add an extra use case, mine is a selectable list of products where the list contents can be filtered by product type.  Each list item needs an href to a different view depending on the current product type.  An example usage would be as follows:
```
<li repeat.for="product of products | arrayFilterOnProperty:'PRODUCT_TYPE': selectedProductType.value">
    <a  route-href="route: product-${product.PRODUCT_TYPE}-view; params.bind: {id:product.id }" click.delegate="$parent.selectProduct(product)"> >    
    <compose view="./product-select-${product.PRODUCT_TYPE}-list-entry.html" view-model.bind="product">
</a>
```

**Comment by EisenbergEffect** [comment] 2016-05-17 15:02
This would be a great opportunity for a community contributions. Someone could add a new bindable property on the route-href that told it not to enforce this constraint...

**Comment by kristianmandrup** [comment] 2016-08-03 19:47
Let's make this *not your grandmother's router*

**Comment by michie1** [comment] 2016-09-10 08:36
I made a solution. Any remarks or suggestions? I could use some advice on how to test this feature/fix.

**Comment by kristianmandrup** [comment] 2016-09-10 10:21
@michie1 I like it :) Pure and simple.

**Comment by JoshMcCullough** [comment] 2016-11-12 04:04
Any movement on this? I load data in `attached` so I can show a loading indicator, but `route-href` is bound before the data is ready. Any other workaround?

**Comment by EisenbergEffect** [comment] 2016-11-12 04:15
There was an issue with the PR I think. I'll review for next week's release and see if we can move this along.

**Comment by nathanchase** [comment] 2017-03-13 05:24
I'd like to see this happen, too. I wrote about my use case here: http://stackoverflow.com/questions/42756084/how-do-you-dynamically-bind-route-href-parameters-in-aurelia

Essentially, the requested behaviors is: "If a route-href has null parameters, just have it ignore them when it generates the URL."

**Comment by esmoore68** [comment] 2017-03-14 13:38
I'm unclear as to why default route.href binding behavior should handle undefined differently than any other binding.

The same properties that cause route-href to throw an error do not throw an error when displayed with ${} or with value.bind.

**Comment by JoshMcCullough** [comment] 2017-03-14 15:33
@esmoore68 Because the contents of `${someVariable}` are not required whereas some route parameters, e.g. `/things/:id/edit`, _are_ required. The route can't be constructed if the `id` parameter is not defined or null.

**Comment by dinkzilla** [comment] 2017-08-08 20:40
@CasiOo's solution, recommended in @michie1's pull request, seems like a pretty good one to me. Still waiting on weigh-in from Aurelia team though it looks like.

**Comment by davismj** [comment] 2017-12-10 10:38
To everyone in this thread, thanks for the input and keeping this conversation going.

I think the problem here is a fundamental misunderstanding of the activate callback. If you have any data that is required in your view anywhere, including route-href, you should load that data and return the corresponding promise in the `activate()` callback. Then, all your data will be available on `bind()`, which is when route-href is set up.

@DevNebulae So what I don't understand about your case is that the function or variable case should just work, provided that function returns the proper value on bind. If you change that data behind the scenes programatically, normal binding rules still apply and the route will be updated.

@jon123 I believe this would work as described. In particular, the `product.PRODUCT_TYPE` variable would be available in this example at bind time. Does it not work?

@JoshMcCullough The problem is that `attached()` is when the dom is ready, and is more suited for things like setting up 3rd party ui tools. `activate()` is where you should be loading your data.

@nathanchase I totally agree with you. This is a problem and something that needs to be fixed. I don't think there's currently an issue for it. If you'd like to open that issue in the route-recognizer repo, I think that is something we should make a priority. However, I don't think that is what is being discussed here.

@esmoore68 I'm not 100% clear on what in fact does happen without a working example, but my guess is that it does work identically to other bindings, and its not that the route-href binding itself is throwing an error, but the underlying `router.generateRoute()` function is throwing the error, which is to be expected.

My problem with the @michie1 PR (#39) is that introduces a new, more complicated way of doing something that already has a best practice. Though pulling it in would not hurt anything, the complexity increase doesn't balance the benefit. Instead, I think this might be more of a training issue that requires better documentation.

That said, I'd love to see some working examples via gist.run so I can make sure that all the uses cases are properly handled with reasonably concise code.

**Comment by JoshMcCullough** [comment] 2017-12-11 01:40
@davismj We do our data loading / API calls in `attached` because it allows the UI to render and show loading indicators as we pull down the data for the view. If we did that in `activate` instead, the user would be waiting for the data to load before any UI is displayed. This makes the app appear slower and the user would question whether anything was happening at all.

Perhaps `route-href` should not build the URL until after `attached` has completed?

**Comment by michie1** [comment] 2017-12-11 05:15
@davismj I can confirm it could be a training issue because my experience with Aurelia and promises was little at that time. An error with a (link to a) short description how to solve the problem would be better than allowing bad practices.

**Comment by StrahilKazlachev** [comment] 2017-12-11 07:41
@JoshMcCullough Any reason why you don't use a *loading indicator* that sits outside the views that are loading?
In short, the way I've organized such things is I have a dedicated custom element that sits outside the `<router-view>` that's loading. Communication is done using the `EventAgrregator`.

**Comment by DevNebulae** [comment] 2017-12-11 09:52
@davismj Keep in mind that I wrote the issue description on March 31st 2016. The use case of my issue was that I wanted the components to register *themselves* to the router so that dynamic links could be generated. I don't exactly know what my use case was, since I haven't worked on the project for well over a year.

**Comment by jon123** [comment] 2017-12-11 11:52
@davismj at the time I wrote that sample code, it did not work.  I worked around the issue at the time.  Unfortunately I am no longer working with Aurelia so I cannot see if it functions in current.   Given its been over a year it may be working.

**Comment by JoshMcCullough** [comment] 2017-12-11 20:43
@StrahilKazlachev We have one-many areas within a view that require data and we often will display loading indicators in each area to communicate that that section is still loading. So it's important to load the view's minimum UI (e.g. sections/headers/text) while we load data in the background to populate the rest.

**Comment by Alexander-Taran** [comment] 2018-03-03 14:51
nothing stops you from wraping up your route-href into if.bind to not render until parameters are ready.. link is usless until they are. No?

might be closed

**Comment by JoshMcCullough** [comment] 2018-03-03 15:08
@Alexander-Taran  I don't like the idea of having to add `if-bind`s everywhere, I think it could be fixed in the framework itself.

**Comment by Alexander-Taran** [comment] 2018-03-03 15:14
Yeah.. I also like breakfast in bed (-:
but.. 'you are holding it wrong' (c)b

you are talking about introducing something to the core framework that will have to be supported..
because of a late binding..
and you are happy with that user could possibly click on a non working link and be frustrated


now here is an idea.. what if there were a possibility to mark something as late bound..

still i belive that
```
<div if.bind='loading'>
 loading
</div>
<div else>
 real content when data is available
</div>
```

is way cleaner and more maintanable
as well as less frustrating

**Comment by EisenbergEffect** [comment] 2018-03-03 21:43
@davismj to triage and decide whether to close or if a new feature is needed.

**Comment by davismj** [comment] 2018-03-05 06:09
I'm closing for lack of interest. I think there might be something here to consider but I need to see some real examples to move forward. Will reopen when the time comes.

**Closed by davismj** 2018-03-05 06:09 UTC
Labels: enhancement

**Comment by Alexander-Taran** [comment] 2018-03-05 09:59
concept of async binding referenced here
https://github.com/aurelia/testing/issues/49

might help OP
