### ISSUE TITLE
Previous views are not removed from the DOM when using swap-order values 'with' or 'before'

### ISSUE THREAD

**Issue by bfil** [aurelia/templating-router#28] opened 2016-06-16 15:36 UTC
I've just updated to the latest version of aurelia and it looks like views under `router-view` elements are left on the DOM when using `swap-order="with"` or `swap-order="before"`, it works just fine with `swap-order="after"`.

Rolling back the 3 templating modules to the previous version fixes the issue.

I've tried to only roll back `templating-router` to version `1.2.1` but the issue persists, only rolling back all 3 modules solves the issue for me.

Let me know if I should raise the issue on another module instead.

**Comment by EisenbergEffect** [comment] 2016-06-16 15:38
@charlespockert Could this be related to the new layout implementation? Can you take a look?

**Comment by charlespockert** [comment] 2016-06-16 16:17
@EisenbergEffect could be, though if you aren't using the layouts it should theoretically be the original code path

Would be useful to add some more test coverage around swaps too to cover this

I'll have a look now

**Comment by charlespockert** [comment] 2016-06-16 16:21
@bfil can you confirm - you rolled back to 1.2.1 on templating-router and the issue persisted, and you are absolutely sure that you were running this version?

@EisenbergEffect I don't believe the layouts feature went in until 2.0.0 with the shadow DOM v1 changes so maybe there's something else in play here...

Can have a look anyway as I have a test repo ready to go

**Comment by bfil** [comment] 2016-06-16 17:04
Yes, with that version of templating-router the issue was still there, it's a bit confusing though, because only downgrading the 2 other templating modules didn't solve the issue, while downgrading all 3 did. 

I might try again, but I think you can try and reproduce the issue with all the latest modules and let me know if you can?

In the mean time when I have some time I'll dig a bit more to see if I can narrow the issue down to one particular module.

**Comment by charlespockert** [comment] 2016-06-17 08:30
@bfil I've not managed to reproduce this exactly - though I have found an issue when using one of the other swap strategies that the `ViewSlot` throws when trying to remove the previous view, just debugging now...

I'm pretty sure this is contributing to your issue but interestingly, despite the issue my skeleton correctly removes the views in Chrome/FF and IE

Will update shortly

**Comment by bfil** [comment] 2016-06-17 08:57
I've just done the following:

```
git clone https://github.com/aurelia/skeleton-navigation.git
cd skeleton-navigation/skeleton-typescript
npm install && jspm install
jspm update
```

Then in `app.html` added `swap-order="with"` to the `router-view`.

`gulp watch`, ignored TypeScript errors on the terminal and opened up Chrome (version 50.0.2661.102)

This is what I get when navigating between views:

![screen shot 2016-06-17 at 09 57 09](https://cloud.githubusercontent.com/assets/660513/16145690/eb9bed48-3471-11e6-8a32-5a0acb509eaa.png)

**Comment by bfil** [comment] 2016-06-17 09:07
Same result in Firefox 47.0:

![screen shot 2016-06-17 at 10 06 19](https://cloud.githubusercontent.com/assets/660513/16145912/3a183962-3473-11e6-8463-2906d013661f.png)

**Comment by charlespockert** [comment] 2016-06-17 09:17
@bfil @EisenbergEffect think I've found this - the `compose` instruction on the `compositionEngine` is handling the `ViewSlot` add/remove itself which is causing the view to not be in the DOM when the swap strategy kicks in

With a few tweaks I've switched to `createController` and then added to the `ViewSlot` manually, this seems to fix the animations and you get the expected results.

Just checking all the bits and should be able to PR this in a mo

**Comment by bfil** [comment] 2016-06-17 09:29
Sounds great, just to be clear, the issue happens regardless of the usage of the aurelia-css-animator plugin.

**Comment by charlespockert** [comment] 2016-06-17 09:33
@bfil that makes sense - though I'd really only expect it to happen when you were using the new layouts feature, are you using that?

**Comment by bfil** [comment] 2016-06-17 09:40
No idea what the new layouts feature is, did you look at how I reproduced it by just cloning the typescript skeleton? Not sure if that project uses the new layouts feature.

**Comment by EisenbergEffect** [comment] 2016-06-17 10:37
@charlespockert Thanks for looking into this! Your description of the problem makes sense. I'll look out for the PR and get it release asap.

**Comment by charlespockert** [comment] 2016-06-17 10:57
@bfil before we can merge the PR - as a precaution, is there any chance you can either patch the `router-view.js` onto the one in the latest version of the templating-router repo in your app and see if it solves your issue?

Here's the PR:

https://github.com/aurelia/templating-router/pull/29

You should just need `router-view.js`

**Comment by charlespockert** [comment] 2016-06-17 11:17
@bfil you can also check out this skeleton clone:

https://github.com/charlespockert/router-test/

The fix to the router view is in the `skeleton-esnext` so you just need to do the usual `npm install` `jspm install` `gulp watch` dance to test it

**Comment by bfil** [comment] 2016-06-17 13:30
Tried to use the new `router-view` and it looks like it's working just fine, great work :) Looking forward for a patch release

**Comment by EisenbergEffect** [comment] 2016-07-09 05:33
Closing since the fix was merged.

**Closed by EisenbergEffect** 2016-07-09 05:33 UTC
